
import { Shipment, Driver, ConstraintItem } from './types';

// Generate dates relative to today
const today = new Date();
const getRelativeDate = (daysOffset: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split('T')[0];
};

// Drivers
export const drivers: Driver[] = [
  { id: "D001", name: "Budi Santoso" },
  { id: "D002", name: "Agus Widodo" },
  { id: "D003", name: "Deni Hermawan" },
  { id: "D004", name: "Joko Susanto" },
  { id: "D005", name: "Rudi Hartono" },
];

// Mock shipments data
export const shipments: Shipment[] = [
  {
    id: "SHP001",
    noSuratJalan: "SJ-001-2025",
    perusahaan: "PT Maju Bersama",
    tujuan: "Jakarta Pusat",
    supir: "Budi Santoso",
    tanggalKirim: getRelativeDate(-5),
    tanggalTiba: getRelativeDate(-3),
    waktuTiba: "14:30",
    status: "terkirim",
    kendala: null,
    qty: 120,
  },
  {
    id: "SHP002",
    noSuratJalan: "SJ-002-2025",
    perusahaan: "CV Sukses Makmur",
    tujuan: "Bandung",
    supir: "Agus Widodo",
    tanggalKirim: getRelativeDate(-4),
    tanggalTiba: getRelativeDate(-2),
    waktuTiba: "15:45",
    status: "terkirim",
    kendala: null,
    qty: 85,
  },
  {
    id: "SHP003",
    noSuratJalan: "SJ-003-2025",
    perusahaan: "PT Global Jaya",
    tujuan: "Surabaya",
    supir: "Deni Hermawan",
    tanggalKirim: getRelativeDate(-3),
    tanggalTiba: null,
    waktuTiba: null,
    status: "tertunda",
    kendala: "Cuaca buruk",
    qty: 200,
  },
  {
    id: "SHP004",
    noSuratJalan: "SJ-004-2025",
    perusahaan: "PT Sentosa Abadi",
    tujuan: "Semarang",
    supir: "Joko Susanto",
    tanggalKirim: getRelativeDate(-3),
    tanggalTiba: null,
    waktuTiba: null,
    status: "gagal",
    kendala: "Kerusakan kendaraan",
    qty: 65,
  },
  {
    id: "SHP005",
    noSuratJalan: "SJ-005-2025",
    perusahaan: "PT Indah Permai",
    tujuan: "Yogyakarta",
    supir: "Rudi Hartono",
    tanggalKirim: getRelativeDate(-2),
    tanggalTiba: getRelativeDate(-1),
    waktuTiba: "10:15",
    status: "terkirim",
    kendala: null,
    qty: 150,
  },
  {
    id: "SHP006",
    noSuratJalan: "SJ-006-2025",
    perusahaan: "CV Duta Express",
    tujuan: "Malang",
    supir: "Budi Santoso",
    tanggalKirim: getRelativeDate(-2),
    tanggalTiba: null,
    waktuTiba: null,
    status: "tertunda",
    kendala: "Kemacetan parah",
    qty: 95,
  },
  {
    id: "SHP007",
    noSuratJalan: "SJ-007-2025",
    perusahaan: "PT Cahaya Logistik",
    tujuan: "Surakarta",
    supir: "Agus Widodo",
    tanggalKirim: getRelativeDate(-1),
    tanggalTiba: null,
    waktuTiba: null,
    status: "tertunda",
    kendala: "Dokumen tidak lengkap",
    qty: 110,
  },
  {
    id: "SHP008",
    noSuratJalan: "SJ-008-2025",
    perusahaan: "PT Sarana Transindo",
    tujuan: "Denpasar",
    supir: "Deni Hermawan",
    tanggalKirim: getRelativeDate(-6),
    tanggalTiba: getRelativeDate(-4),
    waktuTiba: "08:30",
    status: "terkirim",
    kendala: null,
    qty: 175,
  },
  {
    id: "SHP009",
    noSuratJalan: "SJ-009-2025",
    perusahaan: "CV Mega Transport",
    tujuan: "Makassar",
    supir: "Joko Susanto",
    tanggalKirim: getRelativeDate(-5),
    tanggalTiba: null,
    waktuTiba: null,
    status: "gagal",
    kendala: "Barang rusak",
    qty: 80,
  },
  {
    id: "SHP010",
    noSuratJalan: "SJ-010-2025",
    perusahaan: "PT Anugerah Ekspedisi",
    tujuan: "Palembang",
    supir: "Rudi Hartono",
    tanggalKirim: getRelativeDate(-4),
    tanggalTiba: getRelativeDate(-1),
    waktuTiba: "16:20",
    status: "terkirim",
    kendala: null,
    qty: 130,
  },
  {
    id: "SHP011",
    noSuratJalan: "SJ-011-2025",
    perusahaan: "PT Selalu Prima",
    tujuan: "Padang",
    supir: "Budi Santoso",
    tanggalKirim: getRelativeDate(-3),
    tanggalTiba: null,
    waktuTiba: null,
    status: "gagal",
    kendala: "Alamat tidak ditemukan",
    qty: 90,
  },
  {
    id: "SHP012",
    noSuratJalan: "SJ-012-2025",
    perusahaan: "CV Mitra Logistik",
    tujuan: "Manado",
    supir: "Agus Widodo",
    tanggalKirim: getRelativeDate(0),
    tanggalTiba: null,
    waktuTiba: null,
    status: "tertunda",
    kendala: "Sedang dalam perjalanan",
    qty: 140,
  }
];

// Common constraints
export const constraints: ConstraintItem[] = [
  { name: "Cuaca buruk", count: 3 },
  { name: "Kerusakan kendaraan", count: 5 },
  { name: "Kemacetan parah", count: 7 },
  { name: "Dokumen tidak lengkap", count: 2 },
  { name: "Barang rusak", count: 1 },
  { name: "Alamat tidak ditemukan", count: 4 },
  { name: "Sedang dalam perjalanan", count: 8 }
];
