
import { Shipment, Driver, ShipmentStatus } from "./types";

// Mock driver data matching the database structure
export const drivers: Driver[] = [
  { id: "1", name: "MULYADI", licensePlate: "T 9388 TC" },
  { id: "2", name: "BAYU", licensePlate: "B 9104 UXZ" },
  { id: "3", name: "SUYANDI", licensePlate: "B 9681 FXZ" },
  { id: "4", name: "MULYANA", licensePlate: "T 9863 TB" },
  { id: "5", name: "TATANG", licensePlate: "B 9670 FXZ" },
];

// Mock shipment data with driver relations
export const shipments: Shipment[] = [
  {
    id: "1",
    noSuratJalan: "SJ-001/2024",
    perusahaan: "PT Logistik Jaya",
    tujuan: "Jakarta Selatan",
    driverId: "1",
    drivers: { id: "1", name: "MULYADI", license_plate: "T 9388 TC" },
    tanggalKirim: "2024-01-15",
    tanggalTiba: "2024-01-16",
    waktuTiba: "14:30",
    status: "terkirim" as ShipmentStatus,
    kendala: null,
    qty: 50,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "2",
    noSuratJalan: "SJ-002/2024",
    perusahaan: "CV Maju Bersama",
    tujuan: "Bandung",
    driverId: "2",
    drivers: { id: "2", name: "BAYU", license_plate: "B 9104 UXZ" },
    tanggalKirim: "2024-01-16",
    tanggalTiba: null,
    waktuTiba: null,
    status: "tertunda" as ShipmentStatus,
    kendala: null,
    qty: 75,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "3",
    noSuratJalan: "SJ-003/2024",
    perusahaan: "PT Distribusi Nusantara",
    tujuan: "Surabaya",
    driverId: "3",
    drivers: { id: "3", name: "SUYANDI", license_plate: "B 9681 FXZ" },
    tanggalKirim: "2024-01-17",
    tanggalTiba: null,
    waktuTiba: null,
    status: "gagal" as ShipmentStatus,
    kendala: "Macet",
    qty: 100,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "4",
    noSuratJalan: "SJ-004/2024",
    perusahaan: "PT Ekspedisi Prima",
    tujuan: "Yogyakarta",
    driverId: "4",
    drivers: { id: "4", name: "MULYANA", license_plate: "T 9863 TB" },
    tanggalKirim: "2024-01-18",
    tanggalTiba: "2024-01-19",
    waktuTiba: "09:15",
    status: "terkirim" as ShipmentStatus,
    kendala: null,
    qty: 25,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "5",
    noSuratJalan: "SJ-005/2024",
    perusahaan: "CV Cepat Sampai",
    tujuan: "Semarang",
    driverId: "5",
    drivers: { id: "5", name: "TATANG", license_plate: "B 9670 FXZ" },
    tanggalKirim: "2024-01-19",
    tanggalTiba: null,
    waktuTiba: null,
    status: "tertunda" as ShipmentStatus,
    kendala: null,
    qty: 60,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "6",
    noSuratJalan: "SJ-006/2024",
    perusahaan: "PT Logistik Jaya",
    tujuan: "Malang",
    driverId: "1",
    drivers: { id: "1", name: "MULYADI", license_plate: "T 9388 TC" },
    tanggalKirim: "2024-01-20",
    tanggalTiba: "2024-01-21",
    waktuTiba: "16:45",
    status: "terkirim" as ShipmentStatus,
    kendala: null,
    qty: 80,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "7",
    noSuratJalan: "SJ-007/2024",
    perusahaan: "CV Maju Bersama",
    tujuan: "Denpasar",
    driverId: "2",
    drivers: { id: "2", name: "BAYU", license_plate: "B 9104 UXZ" },
    tanggalKirim: "2024-01-21",
    tanggalTiba: null,
    waktuTiba: null,
    status: "tertunda" as ShipmentStatus,
    kendala: null,
    qty: 40,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "8",
    noSuratJalan: "SJ-008/2024",
    perusahaan: "PT Distribusi Nusantara",
    tujuan: "Medan",
    driverId: "3",
    drivers: { id: "3", name: "SUYANDI", license_plate: "B 9681 FXZ" },
    tanggalKirim: "2024-01-22",
    tanggalTiba: null,
    waktuTiba: null,
    status: "gagal" as ShipmentStatus,
    kendala: "Ban Bocor",
    qty: 90,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "9",
    noSuratJalan: "SJ-009/2024",
    perusahaan: "PT Ekspedisi Prima",
    tujuan: "Palembang",
    driverId: "4",
    drivers: { id: "4", name: "MULYANA", license_plate: "T 9863 TB" },
    tanggalKirim: "2024-01-23",
    tanggalTiba: "2024-01-24",
    waktuTiba: "11:20",
    status: "terkirim" as ShipmentStatus,
    kendala: null,
    qty: 65,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "10",
    noSuratJalan: "SJ-010/2024",
    perusahaan: "CV Cepat Sampai",
    tujuan: "Balikpapan",
    driverId: "5",
    drivers: { id: "5", name: "TATANG", license_plate: "B 9670 FXZ" },
    tanggalKirim: "2024-01-24",
    tanggalTiba: null,
    waktuTiba: null,
    status: "tertunda" as ShipmentStatus,
    kendala: null,
    qty: 55,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "11",
    noSuratJalan: "SJ-011/2024",
    perusahaan: "PT Logistik Jaya",
    tujuan: "Makassar",
    driverId: "1",
    drivers: { id: "1", name: "MULYADI", license_plate: "T 9388 TC" },
    tanggalKirim: "2024-01-25",
    tanggalTiba: "2024-01-26",
    waktuTiba: "13:10",
    status: "terkirim" as ShipmentStatus,
    kendala: null,
    qty: 70,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  },
  {
    id: "12",
    noSuratJalan: "SJ-012/2024",
    perusahaan: "CV Maju Bersama",
    tujuan: "Pontianak",
    driverId: "2",
    drivers: { id: "2", name: "BAYU", license_plate: "B 9104 UXZ" },
    tanggalKirim: "2024-01-26",
    tanggalTiba: null,
    waktuTiba: null,
    status: "gagal" as ShipmentStatus,
    kendala: "Mesin Rusak",
    qty: 85,
    trackingUrl: null,
    currentLat: null,
    currentLng: null
  }
];
