// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfcaxmcbeawwnngjnjta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmY2F4bWNiZWF3d25uZ2puanRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjE4OTYsImV4cCI6MjA2MjAzNzg5Nn0.bVzT4-yHaeaTM0RRsKp6FXATa69fEUgwHxSCFFdb5hc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);